// Generated by IB v0.2.10 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation Camera

@end


@implementation ParserError

@end


@implementation NSNotificationCenter

@end


@implementation NSURLRequest

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation Response

@end


@implementation Query

@end


@implementation InvalidURLError

@end


@implementation InvalidFileError

@end


@implementation PeriodicTimer

@end


@implementation Queue

@end


@implementation Timer

@end


@implementation RSSParser

@end


@implementation RSSItem

@end


@implementation InvalidPlayerType

@end


@implementation NilPlayerCallback

@end


@implementation Player

@end


@implementation AppDelegate

@end



